// archive/react-figma-prototype-2026-05-20/src/app/components/modals/LoginModal.tsx
import { useState } from "react";
import { Button } from "../ui/button";
import { Input } from "../ui/input";
import { Label } from "../ui/label";
import { X, Building2 } from "lucide-react";

interface LoginModalProps {
  isOpen: boolean;
  onClose: () => void;
  onLogin: (role: "business_owner" | "tourism_staff" | "admin") => void;
  onRegisterClick: () => void;
}

export function LoginModal({ isOpen, onClose, onLogin, onRegisterClick }: LoginModalProps) {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [rememberMe, setRememberMe] = useState(false);

  if (!isOpen) return null;

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    const normalizedEmail = email.trim().toLowerCase();
    
    // Role detection based on email
    if (normalizedEmail.includes("admin")) {
      onLogin("admin");
    } else if (
      normalizedEmail.includes("staff") ||
      normalizedEmail.includes("tourism")
    ) {
      onLogin("tourism_staff");
    } else {
      onLogin("business_owner");
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-black/60 backdrop-blur-sm"
        onClick={onClose}
      />
      
      {/* Modal */}
      <div className="relative bg-white rounded-2xl shadow-2xl w-full max-w-md max-h-[90vh] overflow-y-auto">
        {/* Close Button */}
        <button
          onClick={onClose}
          className="absolute right-4 top-4 rounded-full p-2 hover:bg-gray-100 transition-colors z-10"
        >
          <X className="size-5 text-gray-500" />
        </button>

        {/* Content */}
        <div className="p-8">
          {/* Logo */}
          <div className="flex items-center justify-center mb-6">
            <div className="flex items-center justify-center size-16 rounded-full bg-[var(--color-gov-blue)]">
              <Building2 className="size-8 text-white" />
            </div>
          </div>

          {/* Header */}
          <div className="text-center mb-8">
            <h2 className="text-2xl mb-2">Welcome Back</h2>
            <p className="text-muted-foreground">
              Sign in to your Business Accreditation account
            </p>
          </div>

          {/* Form */}
          <form onSubmit={handleSubmit} className="space-y-5">
            <div className="space-y-2">
              <Label required>Email Address</Label>
              <Input
                type="email"
                placeholder="your.email@example.com"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                required
              />
            </div>

            <div className="space-y-2">
              <Label required>Password</Label>
              <Input
                type="password"
                placeholder="Enter your password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                required
              />
            </div>

            <div className="flex items-center justify-between">
              <label className="flex items-center gap-2 cursor-pointer">
                <input
                  type="checkbox"
                  checked={rememberMe}
                  onChange={(e) => setRememberMe(e.target.checked)}
                  className="rounded"
                />
                <span className="text-sm">Remember me</span>
              </label>
              <a href="#" className="text-sm text-[var(--color-gov-blue)] hover:underline">
                Forgot password?
              </a>
            </div>

            <Button type="submit" className="w-full" size="lg">
              Sign In
            </Button>

            <div className="text-center pt-4 border-t border-border space-y-4">
              <div>
                <p className="text-sm text-muted-foreground mb-2">
                  New business owner?{" "}
                  <button
                    type="button"
                    onClick={onRegisterClick}
                    className="text-[var(--color-gov-blue)] hover:underline font-medium"
                  >
                    Create an account
                  </button>
                </p>
                <p className="text-xs text-muted-foreground">
                  Staff and admin accounts are managed by the LGU administrator.
                </p>
              </div>

              {/* Demo Accounts */}
              <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                <p className="text-xs font-medium text-blue-900 mb-2">Demo Accounts for Testing:</p>
                <div className="space-y-2 text-left">
                  <div className="text-xs">
                    <p className="font-medium text-blue-900">Business Owner:</p>
                    <p className="text-blue-700">owner@business.com</p>
                  </div>
                  <div className="text-xs">
                    <p className="font-medium text-blue-900">Tourism Staff/Officer:</p>
                    <p className="text-blue-700">staff@tourism.gov.ph</p>
                  </div>
                  <div className="text-xs">
                    <p className="font-medium text-blue-900">Administrator:</p>
                    <p className="text-blue-700">admin@tourism.gov.ph</p>
                  </div>
                  <p className="text-xs text-blue-600 italic mt-2">
                    Password: Any password (demo mode)
                  </p>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}

// frontend/src/modules/accreditation/components/modals/LoginModal.vue
<template>
  <div v-if="open" class="public-modal-backdrop" @click.self="$emit('close')">
    <form class="login-card modal-login-card" @submit.prevent="submit">
      <button class="login-back" type="button" @click="$emit('close')">Back</button>

      <div class="login-logo">
        <Building2 :size="32" />
      </div>

      <div class="login-heading">
        <h1>Welcome Back</h1>
        <p>Sign in to your Business Accreditation account</p>
      </div>

      <label>Email Address
        <input
          v-model="form.email"
          type="email"
          placeholder="your.email@example.com"
          required
        />
      </label>

      <label>Password
        <div class="password-field">
          <input
            v-model="form.password"
            :type="showPassword ? 'text' : 'password'"
            placeholder="Enter your password"
            required
          />
          <button type="button" @click="showPassword = !showPassword">
            {{ showPassword ? "Hide" : "Show" }}
          </button>
        </div>
      </label>

      <div class="login-options">
        <label class="remember-line">
          <input v-model="rememberMe" type="checkbox" />
          <span>Remember me</span>
        </label>
        <a href="#">Forgot password?</a>
      </div>

      <p v-if="error" class="form-error">{{ error }}</p>
      <div v-if="verificationUrl" class="verification-panel">
        <p>Click below to verify this business-owner account.</p>
        <a class="btn primary" :href="verificationUrl">Verify Email</a>
      </div>

      <button class="btn primary full large" type="submit">Sign In</button>

      <div class="login-divider">
        <p>
          New business owner?
          <button class="link-button" type="button" @click="$emit('switch-register')">
            Create an account
          </button>
        </p>
        <small>Staff and admin accounts are managed by the LGU administrator.</small>
      </div>

      <div class="demo-box">
        <p>Demo Accounts for Testing</p>
        <div class="demo-list">
          <button type="button" @click="fillDemo('john@sunsetresort.com')">
            Business Owner
            <span>john@sunsetresort.com</span>
          </button>
          <button type="button" @click="fillDemo('maria.santos@tourism.gov.ph')">
            Tourism Staff / Officer
            <span>maria.santos@tourism.gov.ph</span>
          </button>
          <button type="button" @click="fillDemo('system.admin@tourism.gov.ph')">
            System Administrator
            <span>system.admin@tourism.gov.ph</span>
          </button>
        </div>
        <small>Password: password123</small>
      </div>
    </form>
  </div>
</template>

<script setup>
import { reactive, ref } from "vue";
import { useRouter } from "vue-router";
import { Building2 } from "@lucide/vue";
import { useAuthStore } from "@/stores/authStore";

defineProps({
  open: { type: Boolean, required: true },
});

defineEmits(["close", "switch-register"]);

const router = useRouter();
const auth = useAuthStore();
const error = ref("");
const verificationUrl = ref("");
const rememberMe = ref(false);
const showPassword = ref(false);
const form = reactive({ email: "", password: "" });

async function submit() {
  error.value = "";
  verificationUrl.value = "";
  try {
    await auth.login(form);
    router.push("/accreditation/app/dashboard");
  } catch (err) {
    error.value = err.response?.data?.message || "Unable to sign in.";
    verificationUrl.value = err.response?.data?.verificationUrl || "";
  }
}

function fillDemo(email) {
  form.email = email;
  form.password = "password123";
}
</script>
